### ISSUE TITLE
Nuovi campi

### ISSUE THREAD

**Issue by Francesco2595** [edoardopelli/joinup#111]
Servirebbe aggiungere i campi:

flagPrivacyBusiness: string in anagrafica BUSINESS
tipoUtente: string in anagrafica BUSINESS
tipoEvento: int (conterrà l’id del settore merceologico di riferimento) in EVENTI
visibleAll: Boolean in EVENTI

**Comment by Francesco2595** [comment]
Ho scordato una cosa: aggiungiamo anche un flagCondizioniPremium in anagrafica CONSUMER, sempre tipo string

**Comment by edoardopelli** [comment]
tipoEvento lo chiamerei idSettoreMerceologico per omogeneità dei dati
