### ISSUE TITLE
Nuova collection "marketplace"

### ISSUE THREAD

**Issue by Francesco2595** [edoardopelli/joinup#112]
Servirebbe creare una nuova collection marketplace con più o meno gli stessi dati degli annunci con in più prezzo e foto, li ricapitolo qui:

  "codBene": "string",
  "cuc": 0,
  "descrizione": "string",
  "titolo": "string",
  "stato": "APERTO",
  "indirizzo": "string",
  "numeroCivico": "string",
  "idProvincia": 0,
  "citta": "string",
  "latitudine": 0,
  "longitudine": 0,
  "cap": "string",
  "active": true,
  "dataCreazione": (se riesci ad impostarla al momento dell'inserimento meglio)
  "prezzo": "string"
  "foto": [url]

Servizi marketplace:
    1. Lista di tutti gli oggetti messi in vendita dal più vicino al più lontano;
    2. Lista di tutti gli oggetti messi in vendita dal più vicino al più lontano filtrati per codice bene;
    3. Inserimento, modifica e cancellazione;
    4. Lista degli oggetti messi in vendita da un determinato cuc;
    5. Prevedere caricamento foto per l’oggetto messo in vendita (per ora prevediamo di mettere una foto sola ma sarebbe ottimo farlo in modo tale che se dovessimo decidere di caricare più foto per il singolo oggetto non sia un problema)

**Comment by Francesco2595** [comment]
Edo perdonami ma forse c'è stata una incomprensione sui primi due punti, con "dal più vicino al più lontano" intendevo dire come per gli eventi, quindi passando lat e long e restituirmeli in ordine di vicinanza da quel punto, una cosa del tipo

/marketplaces/lat/long/start/max
/marketplaces/codBene/lat/long/start/max

Scusami, la prossima volta metto anche un esempio di endpoint per essere più chiaro

**Comment by edoardopelli** [comment]
non vedo malfunzionamenti.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/35376749/166098374-74aae0b8-b2aa-4fd5-9631-c5c70a8949ec.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/35376749/166098395-dacaa65a-5463-4779-b2cc-41185ecd45cb.png">

**Comment by Francesco2595** [comment]
Se faccio la post con /rest/marketplaces funziona (ma chiaramente non mette la foto), provando successivamente a chiamare /rest/marketplaces/with/photos mi ritorna un oggetto vuoto (come ti ho fatto vedere nell'esempio) non capisco come lo devo utilizzare, sarebbe utile un esempio completo

**Comment by edoardopelli** [comment]
all'url manca l'idMarketplace. vedi prima foto.

**Comment by Francesco2595** [comment]
Hai ragione ma ora ottengo un 415, questa è la post (ti invio sempre il pastebin dato che con il base64 di mezzo diventa illeggibile qui) https://pastebin.com/4YZfdxxt psw GWT7k1JqFJ

L'errore è:

> {
> 	"timestamp": "2022-05-11T10:30:09.619+0000",
> 	"status": 415,
> 	"error": "Unsupported Media Type",
> 	"message": "Content type 'application/json' not supported",
> 	"path": "/viraljoin/rest/marketplaces/with/photos/626e5d9b6344590001eedf4e"
> }

Ma sulla documentazione vedo che 'application/json' è il media type, sbaglio qualcosa?

<img width="686" alt="Screenshot 2022-05-11 at 12 35 55" src="https://user-images.githubusercontent.com/52498065/167830520-4b50c5bc-6e1a-4690-9705-6a02296e8f50.png">

**Comment by edoardopelli** [comment]
il servizio consuma questo 
<img width="276" alt="image" src="https://user-images.githubusercontent.com/35376749/168216691-2608c193-efe3-4830-b6bd-ccc107c83055.png">

**Comment by Francesco2595** [comment]
Okay mi sembra di averlo fatto funzionare, quindi adesso ottengo una cosa del genere:

> [
> 	{
> 		"id": "626e5d9b6344590001eedf4e",
> 		"idProvincia": 1996,
> 		"cuc": 1079044605,
> 		"latitudine": 45,
> 		"longitudine": 7,
> 		"codBene": "string",
> 		"descrizione": "Prova",
> 		"titolo": "Test",
> 		"indirizzo": "Via Antonio Canova",
> 		"numeroCivico": "20",
> 		"citta": "Torino",
> 		"prezzo": 35.5,
> 		"cap": "10126",
> 		"stato": "APERTO",
> 		"active": true,
> 		"dataCreazione": null,
> 		"idPhotos": [
> 			"627e82c96344590001e8b3e1"
> 		],
> 		"coordinates": [
> 			0.0,
> 			0.0
> 		]
> 	}
> ]

Adesso come posso riprendere l'immagine? Perché non vedo nessun endpoint a cui passare l'id delle foto, non so se è perché ci sono problemi con lo swagger

**Comment by edoardopelli** [comment]
aggiunto ora. 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/35376749/168441165-793ba8ee-c9ac-4e81-94fb-e4a3085bfbd2.png">

**Comment by Francesco2595** [comment]
Inserimento: Funziona
GET della foto tramite id: Funziona

GET per latitudine e longitudine: non funziona

> GET /rest/marketplaces/{long}/{lat}/{start}/{max}

Response:

```
{
	"timestamp": "2022-05-25T14:39:43.705+0000",
	"status": 500,
	"error": "Internal Server Error",
	"message": "Query failed with error code 291 and error message 'error processing query: ns=viraljoin.marketplaces limit=10Tree: GEONEAR  field=coordinates maxdist=1.79769e+308 isNearSphere=0\nSort: {}\nProj: {}\n planner returned error :: caused by :: unable to find index for $geoNear query' on server mongodb:27017; nested exception is com.mongodb.MongoQueryException: Query failed with error code 291 and error message 'error processing query: ns=viraljoin.marketplaces limit=10Tree: GEONEAR  field=coordinates maxdist=1.79769e+308 isNearSphere=0\nSort: {}\nProj: {}\n planner returned error :: caused by :: unable to find index for $geoNear query' on server mongodb:27017",
	"path": "/viraljoin/rest/marketplaces/7.672567/45.0445607/0/10"
}
```

**Comment by edoardopelli** [comment]
mancava un indice sul db. fammi sapere se ora va e soprattutto va prova anche in demo e prod
