### ISSUE TITLE
Nuovo servizio interessi

### ISSUE THREAD

**Issue by Francesco2595** [edoardopelli/joinup#114]
Servirebbe un nuovo servizio per gli interessi:

1. Lista di tutti gli utenti con un certo interesse in una certa provincia (l’interesse è formato da cuc e settore merceologico, quindi bisognerebbe poter tirare giù, per esempio, tutti gli utenti di Torino che sono interessati all’informatica) interessis/{{idProvincia}}/{{idSettoreMerceologico}};

**Comment by edoardopelli** [comment]
il campo idProvincia non c'è sulla collection interessi. magari è il caso di aggiungerlo? al momento un dato del genere non riusciamo ad ottenerlo.

**Comment by Francesco2595** [comment]
Però qui il problema è che se uno user cambia provincia bisogna cambiare tutti gli idProvincia dei suoi interessi, forse bisognerebbe renderlo un attributo del consumer, pensi sia un casino?

**Comment by edoardopelli** [comment]
l'idProvincia esiste già nel consumer. ora studio come fare la query

**Comment by edoardopelli** [comment]
ho portato in test, verifica se ottieni i dati corretti. 

/anagraficautenticonsumers/interessi/{idProvincia}/{idSettore}

P.S. purtroppo lo swagger non funziona più, devo capire perché.

**Comment by Francesco2595** [comment]
Sembra funzionare ma non capisco una cosa, ho fatto la chiamata:

> /rest/anagraficautenticonsumers/interessi/1997/1688

Ed il risultato è stato:

> [
> 	{
> 		"id": "627e7a526344590001e8b39a",
> 		"idInteresse": -421015463,
> 		"cuc": 1079044605,
> 		"idSettoreMerceologico": 1688,
> 		"consumers": []
> 	},
> 	{
> 		"id": "627e7b366344590001e8b3cd",
> 		"idInteresse": 219108889,
> 		"cuc": 815246624,
> 		"idSettoreMerceologico": 1688,
> 		"consumers": []
> 	}
> ]

Il che è corretto, non mi spiego solo perché ci sia l'array "consumers" e perché sia vuoto, non mi dà fastidio quindi puoi anche lasciarlo così ma non so se volevi facesse qualcosa.

Altra cosa che probabilmente non si potrà fare: si riesce ad avere almeno nome, cognome e mail dei cuc? Mi eviterei 1+n chiamate per mostrare a video il nome dei cuc a chi fa la ricerca (se proprio non si può o ti incasina troppo la query lascia così).

**Comment by edoardopelli** [comment]
Sulla tabella consumers non esistono dati per idProvincia 1997

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/35376749/168319745-b3f9bc01-0ab5-44c7-a5a2-10bfea6d178e.png">

**Comment by Francesco2595** [comment]
Hai ragione, non ci avevo fatto caso, in questo caso non dovrebbe ritornare 404? Perché non esistono utenti in quella provincia con quell'interesse. Provando con 1996 effetivamente funziona correttamente e l'array consumers è valorizzato

**Comment by edoardopelli** [comment]
Non essendo un db relazionale funziona in maniera leggermente diversa. Ad esempio se tu cerchi per 1996/1671 avrai un risultato come quello in calce. I due risultati al fondo non hanno idProvincia valorizzato e quindi non hanno consumer associati. Il database è un  po’ sporco. Io metterei il campo idProvincia obbligatorio.

[
    {
        "id": "606db847acce2a4e9adb21b6",
        "idInteresse": -320373560,
        "cuc": 1079044605,
        "idSettoreMerceologico": 1671,
        "consumers": [
            {
                "cuc": 1079044605,
                "idProvincia": 1996,
                "cucma": 119,
                "nome": "Francesco",
                "cognome": "Milito",
                "dataDiNascita": "1995-04-25T00:00:00.000+0000",
                "luogoDiNascita": "",
                "indirizzoResidenza": "Via Antonio Canova",
                "tipoUtente": "Admin",
                "coordinates": [
                    7.6725684,
                    45.0445822
                ],
                "latitudinePosizioneAttuale": 45.0445822,
                "longitudinePosizioneAttuale": 7.6725684,
                "cap": "10126",
                "citta": "TORINO",
                "codiceFiscale": "",
                "sesso": "M",
                "telefono": "3488456559",
                "flagPrivacy": "S",
                "email": ***@***.***",
                "password": "YlJW7eNN7bsYuaxFHPsaCXrnf9Y=",
                "iban": "",
                "dataScadenzaProssimoRinnovo": "2021-04-05T22:00:00.000+0000",
                "importoPagamentoSospeso": 5.25,
                "emailPaypal": "",
                "flagProfile": true,
                "flagInteresseEProposteLavorative": "N",
                "cittadinanza": "Italiana",
                "salt": "sWlgeBL86Gtfbb/ATQqaOMdnd2g=",
                "tokenAccesso": "kUz67mdb9TmxhSZq9FmqIgBjWlu1Pcy3LHgxknzADxwm8jqplJ0l4mlyJBLtDnoSOGz7WlgvDIQFCd0jovZikeAMvAo8zylbTY88",
                "dataUltimoAccesso": 1648942777712,
                "durataTokenAccesso": 604800000,
                "mobileMaster": "3355844753",
                "smsConfirmed": "S",
                "numeroCivico": "20",
                "couponUtilizzabili": 7,
                "couponRegalabili": 8
            }
        ]
    },
    {
        "id": "60ca03be6344590001f31388",
        "idInteresse": -85679684,
        "cuc": 1631438686,
        "idSettoreMerceologico": 1671,
        "consumers": []
    },
    {
        "id": "6141e2c96344590001c0d7eb",
        "idInteresse": -1437021550,
        "cuc": 1760717187,
        "idSettoreMerceologico": 1671,
        "consumers": []
    }
]

**Comment by Francesco2595** [comment]
Ti segnalo che in questo momento il servizio ritorna sempre 404 con body

> {
> 	"timestamp": "2022-05-17T08:01:32.414+0000",
> 	"status": 404,
> 	"error": "Not Found",
> 	"message": "No message available",
> 	"path": "/viraljoin/rest/anagraficautenticonsumers/interessi/1996/1671"
> }

**Comment by edoardopelli** [comment]
per sbaglio avevo cancellato il path del servizio. ora va

**Comment by Francesco2595** [comment]
Puoi portare in demo e prod
