### ISSUE TITLE
Inserimento campi

### ISSUE THREAD

**Issue by Francesco2595** [edoardopelli/joinup#124]
Servirebbe inserire i seguenti campi nelle seguenti collection:

In ricercapersonale inserire i campi:

- indirizzo
- cap
- numeroCivico
- telefono
- email

In prestazioni inserire i campi:

- città
- email
- telefono

In annunci inserire i campi:

- email
- telefono

**Comment by edoardopelli** [comment]
sto portando in test

**Comment by Francesco2595** [comment]
Puoi portare in demo e prod
