### ISSUE TITLE
Collection scontrini

### ISSUE THREAD

**Issue by Francesco2595** [edoardopelli/joinup#125]
Servirebbe creare una nuova collection scontrini con i seguenti campi:

- cuc
- dataInserimento
- dataScontrino
- dataAccettazione
- importoScontrino (decimale)
- importoAccettato (decimale)
- stato (String)
- foto
- note

Dopo di che servirebbero i seguenti servizi:

1. Servizio che restituisca tutti gli scontrini di un utente scontrinis/{cuc}
2. Servizio che restituisca tutti gli scontrini in un determinato mese (qui fai come meglio credi, o ti passo il mese e mi restituisci tu tutti quelli che fanno parte di quel mese oppure ti do una dataInizio e dataFine e mi restituisci tutti quelli che sono compresi nel range) la data da prendere come riferimento è dataScontrino
3. Servizio come al punto 2 che restituisca tutti gli scontrini in un determinato mese e con uno stato che passo, del tipo scontrinis/{dataDal}/{dataAl}/{stato} stato è un flag che utilizziamo per sapere se l’accettazione è in elaborazione “E”, accettato “A”, rifiutato “R”
4. Servizio che mi permetta di caricare la foto dello scontrino
5. Servizio che mi permetta di ricevere la foto dello scontrino a fronte di un id

I servizi te li ho messi qui per comodità ma se pensi sia meglio creare una issue per ogni cosa dimmelo che lo faccio.

**Comment by edoardopelli** [comment]
in test

**Comment by Francesco2595** [comment]
I servizi che ci sono fino ad ora funzionano, devo testare ancora le foto. Mi sono accorto che c'è un servizio in più da fare:

Servizio che restituisca tutti gli scontrini di un utente per un dato periodo di tempo scontrinis/{cuc}/{from}/{to}

**Comment by edoardopelli** [comment]
messo in test
