### ISSUE TITLE
GET scontrini per cuc from to

### ISSUE THREAD

**Issue by Francesco2595** [edoardopelli/joinup#130]
Il servizio

> /rest/scontrinis/find/bydatascontrino/{cuc}/{from}/{to}/{start}/{max}

/rest/scontrinis/find/bydatascontrino/1079044605/2022-07-01/2022-08-01/0/10

restituisce errore 500 con il messaggio

{
	"timestamp": "2022-07-18T13:42:40.639+0000",
	"status": 500,
	"error": "Internal Server Error",
	"message": "Ambiguous handler methods mapped for '/viraljoin/rest/scontrinis/find/bydatascontrino/1079044605/2022-07-01/2022-08-01/0/10': {public org.springframework.http.ResponseEntity com.sn.vj.endpoints.ScontriniEndpoint.findByDataScontrinoAndCuc(java.lang.String,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.Integer), public org.springframework.http.ResponseEntity com.sn.vj.endpoints.ScontriniEndpoint.findByDataScontrino(java.lang.String,java.lang.String,com.sn.vj.dto.enums.StatoScontrino,java.lang.Integer,java.lang.Integer)}",
	"path": "/viraljoin/rest/scontrinis/find/bydatascontrino/1079044605/2022-07-01/2022-08-01/0/10"
}

**Comment by edoardopelli** [comment]
cambio la chiamata per cui in /scontrinis/find/bydatascontrino/and/cuc/{cuc}/{from}/{to}/{start}/{max}
