### ISSUE TITLE
GET scontrini per cuc stato from to

### ISSUE THREAD

**Issue by Francesco2595** [edoardopelli/joinup#131]
Servirebbe un servizio come 

> /rest/scontrinis/find/bydatascontrino/{cuc}/{from}/{to}/{start}/{max}

Ma che filtri anche per "stato" quindi una cosa del tipo

> /rest/scontrinis/find/bydatascontrino/{cuc}/{stato}/{from}/{to}/{start}/{max}

**Comment by edoardopelli** [comment]
creo servizio /scontrinis/find/bydatascontrino/and/cuc/and/stato/{cuc}/{stato}/{from}/{to}/{start}/{max}
